routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('user','UserController');

Route::get('user-list-excel', 'UserController@exportExcel')->name('user.excel');

app/States.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class States extends Model
{
    //
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'last_name', 'identification', 'phone', 
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use App\States;
use Maatwebsite\Excel\Facades\Excel;
use App\Exports\UsersExport;

class UserController extends Controller
{
    public function index(Request $request)
    {
        $users = User::orderBy('id', 'DESC')->paginate();
        /*$usercount = User::count();
        
        if ($usercount == 5) {
            //dd("verdadero");
            $random_number= (random_int(1, 5));
        } else {
            dd("falso");
        }
        $userwiner = User::where('id', $random_number);*/

        return view('user.index', compact('users'));
    }

    public function create()
    {
        $stateses = States::orderBy('id', 'DESC')->paginate();

        return view('user.create', compact('stateses'));
    }

    public function store(Request $request)
    {
        $user = new User($request->all());
    
        $user->save();

        return redirect()->route('user.index')->with('info', 'Etiqueta creada con exito');
    }

    public function exportExcel()
    {
        return Excel::download(new UsersExport, 'user-list.xlsx');
    }

    public function show($id)
    {
        $user = User::find($id);

        return view('user.show', compact('user'));
    }

    public function edit($id)
    {
        $user = User::find($id);

        return view('user.edit', compact('user'));
    }

    public function update(Request $request, $id)
    {
        $user = User::find($id);

        $user->fill($request->all())->save();

        return redirect()->route('user.index', $user->id)
            ->with('info', 'Etiqueta actualizada con exito');
    }

}

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.4.1.js" integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU=" crossorigin="anonymous"></script>
</head>
<body>
    <div class="container">
        @yield('content')
    </div>
    @yield('script')
</body>
</html>

resources/views/user/create.blade.php
@extends('layouts.app')

@section('content')

<div class= "container py-5">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="card card-body">    
                <form action="{{ route('user.store') }}" method="POST">
                    {{ csrf_field() }} 
                    <div class="form-group">
                        <label for="exampleInputEmail1">Nombre:</label>
                        <input type="text" class="form-control" id="name" pattern="{1,15}" placeholder="Nombre" maxlength="120" name="name" required>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Apellido:</label>
                        <input type="text" class="form-control" id="last_name" aria-describedby="emailHelp" placeholder="Apellido" maxlength="120" name="last_name" required>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Cédula:</label>
                        <input type="number" class="form-control" id="identification" aria-describedby="emailHelp" placeholder="Cédula" maxlength="120" name="identification" required>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Celular:</label>
                        <input type="number" class="form-control" id="phone" aria-describedby="emailHelp" placeholder="Celular" maxlength="120" name="phone" required>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Correo:</label>
                        <input type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Correo" maxlength="120" name="email" required>
                    </div>
                    <div class="checkbox">
                        <label class="small">
                            <input name="terms" type="checkbox" required>Autorizo el tratamiento de mis datos de acuerdo con la
                            finalidad establecida en la política de protección de datos personales.<a href="#">Haga clic aquí</a>
                        </label>
                    </div>
                    
                    <button type="submit" class="btn btn-primary">Guardar</button>
                    <a href="{{ url('/') }}"> regresar</a>
                </form>
            </div>        
        </div>        
    </div>    
</div>

@endsection

@section('script')

<script type="text/javascript">
    var input = document.getElementById('name');
    var input = document.getElementById('last_name');
    var input = document.getElementById('identification');
    var input = document.getElementById('phone');
    var input = document.getElementById('email');

    input.oninvalid = function(event) {
        event.target.setCustomValidity('Campo requerido');
    }

</script>

@stop

resources/views/user/edit.blade.php
@extends('layouts.app')

@section('content')

<div class= "container py-5">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <div class="card card-body">  
                <form action="{{ route('user.update', $user->id) }}" method="POST"> 
                    {{ method_field('PUT') }}
                    {{ csrf_field() }}
                    <div class="form-group">
                        <label for="exampleInputEmail1">Nombre:</label>
                        <input type="text" class="form-control" id="name" aria-describedby="emailHelp" placeholder="Nombre" maxlength="120" name="name" value="{{ $user->name }}" required>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Apellido:</label>
                        <input type="text" class="form-control" id="last_name" aria-describedby="emailHelp" placeholder="Apellido" maxlength="120" name="last_name" value="{{ $user->last_name }}" required>
                    </div>
                    <div class="form-group">
                            <label for="exampleInputEmail1">Cédula:</label>
                            <input type="text" class="form-control" id="identification" aria-describedby="emailHelp" placeholder="Cédula" maxlength="120" name="identification" value="{{ $user->identification }}"  required>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Celular:</label>
                            <input type="text" class="form-control" id="phone" aria-describedby="emailHelp" placeholder="Celular" maxlength="120" name="phone" value="{{ $user->phone }}" required>
                        </div>
                        <div class="form-group">
                            <label for="exampleInputEmail1">Correo:</label>
                            <input type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Correo" maxlength="120" name="email" value="{{ $user->email }}" required>
                        </div>
                    <button type="submit" class="btn btn-primary">Guardar</button>
                    <a href="{{ route('user.index') }}"> regresar</a>
                </form>
            </div>
        </div>
    </div>
</div>

@endsection

@section('script')

<script type="text/javascript">
    var input = document.getElementById('name');
    var input = document.getElementById('last_name');
    var input = document.getElementById('identification');
    var input = document.getElementById('phone');
    var input = document.getElementById('email');

    input.oninvalid = function(event) {
        event.target.setCustomValidity('Campo requerido');
    }

</script>

@stop

resources/views/user/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container py-5">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-6 mx-auto">                               
                    <div class="card rounded-0">
                        <div class="card-header">
                            <h3 class="">Listado de usuarios</h3>
                            <a href="{{ route('user.create') }}" class="btn btn-sm btn-primary pull-right">
                                 Crear
                            </a>
                            <a href="{{ url('/') }}" class="btn btn-sm btn-primary pull-right">
                                Inicio
                            </a>
                        </div>
                        <div class="card-body">
                            <table class="table table-striped table-hover">
                                <thead>
                                     Clic <a href="{{ route('user.excel') }}">aquí</a> para descargar excel
                                    <tr>
                                        <th width="10px">ID</th>
                                        <th>Nombre</th>
                                        <th>Cédula</th>
                                        <th colspan="3">&nbsp</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($users as $user)
                                        <tr>
                                            <td>{{ $user->id }}</td> 
                                            <td>{{ $user->name }}</td> 
                                            <td>{{ $user->identification }}</td> 
                                            <td width="10px">
                                             <a href="{{ route('user.show', $user->id) }}" class="btn btn-sm btn-default">
                                                Ver
                                             </a>
                                        </td>
                                            <td width="10px">
                                                <a href="{{ route('user.edit', $user->id) }}" class="btn btn-sm btn-default">
                                                    Editar
                                                </a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>     
                    </div>
                </div>
            </div>
        </div>
           
    </div>
        
</div>
    
@endsection

resources/views/user/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container py-5">
    <div class="row">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-6 mx-auto">
    
                    <div class="card rounded-0">
                        <div class="card-header">
                            <h3 class="">Listado de usuarios</h3>
                            <a href="{{ route('user.create') }}" class="btn btn-sm btn-primary pull-right">
                                 Crear
                            </a>
                            <a href="{{ route('user.index') }}" class="btn btn-sm btn-primary pull-right">
                                Volver
                            </a>
                        </div>
                        <div class="card-body">
                            <div class="panel-body">
                                <p><strong>Id: </strong>{{ $user->id }}</p>
                                <p><strong>Nombre: </strong>{{ $user->name }}</p>
                                <p><strong>Slug: </strong>{{ $user->last_name }}</p>
                                <p><strong>Cédula: </strong>{{ $user->identification }}</p>
                                <p><strong>Celular: </strong>{{ $user->phone }}</p>
                                <p><strong>Correo: </strong>{{ $user->email }}</p>
                            </div>
                        </div>     
                    </div>
                </div>
            </div>
        </div>
           
    </div>
        
</div>
    
@endsection